### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by thomas992** [coderedart/luaegui#3]
Expect a branch of [tealr_doc_gen](https://github.com/lenscas/tealr_doc_gen) with a different HTML presentation. I am very particular about HTML, CSS. The documentation is currently split into two on the left, I think that is of poor design. Fields of any specific function could be expanded upon clicking, the entire left column would be the header so the website is always full width. There might be a lot of extra screen space exposed after scrolling down, I think we could let people enable 3d backgrounds like a solar system or aquarium with interactive fish in the future. I will write some tutorials in markdown and include that as well. We could use this project to display the tutorials, and let them interact with the examples. The security of the project should eventually be safe enough to make a website like Pastebin but for EGui Lua.

**Comment by coderedart** [comment]
I have moved away from tealr, as i wanted to go all in with Roblox Luau backend.

As you said, security is very important. And `Luau` runs a *lot* of user provided scripts on roblox servers, so we know they will take security seriously. 

I am still looking for ideas on how to add docs for this library, but i will create a more focused and detailed issue separately for that. I want to render the documentation inside egui itself, so that people can browse docs while they are scripting egui with lua. 

I will be closing this issue for now, but do create a new one if you feel like there's a better way to add documentation.
